name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "MATTAR Dashboard.csproj"

      - name: Publish Blazor WASM
        run: dotnet publish "MATTAR Dashboard.csproj" -c Release -o publish \
      --no-restore \
      -p:BlazorEnableCompression=false \
      -p:BaseHref="/${{ github.event.repository.name }}/"

      - name: Add .nojekyll
        run: touch publish/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          publish_branch: gh-pages
